repos:
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v2.3.1
  hooks:
  - id: stylua
- repo: local
  hooks:
  - id: luacheck
    name: Statically check Lua files
    files: \.lua$
    language: system
    entry: luacheck
  - id: build-html-website
    name: Build website and check HTML with v.Nu Checker
    files: \.html$
    language: script
    entry: tools/build-website.sh
    pass_filenames: false
