local fp = require("filepaths")

describe("fp", function()
  describe(".base_game_name()", function()
    it("should handle a .p8 file name without dash", function()
      assert.equal("vampire_vs_pope_army", fp.base_game_name("vampire_vs_pope_army.p8"))
    end)
    it("should handle a .p8.png file name without dash", function()
      assert.equal("vampire_vs_pope_army", fp.base_game_name("vampire_vs_pope_army.p8.png"))
    end)
    it("should handle a .p8 file name with a dash", function()
      assert.equal("vampire_vs_pope_army", fp.base_game_name("vampire_vs_pope_army-0.p8"))
    end)
    it("should handle a .p8.png file name with a dash", function()
      assert.equal("vampire_vs_pope_army", fp.base_game_name("vampire_vs_pope_army-0.p8.png"))
    end)
  end)

  describe(".as_po_filepath()", function()
    it("should simply return the same string when a valid .po file path is provided", function()
      local valid_po_filepath = "games/vampire_vs_pope_army/fr-FR.po"
      assert.equal(valid_po_filepath, fp.as_po_filepath("vampire_vs_pope_army-0.p8", valid_po_filepath))
    end)
    it("should return a valid .po file path when a .p8 file is provided", function()
      assert.equal("games/vampire_vs_pope_army/fr-FR.po", fp.as_po_filepath("vampire_vs_pope_army-0.p8", "fr-FR"))
    end)
    it("should handle an absolute path", function()
      assert.equal("games/vampire_vs_pope_army/fr-FR.po", fp.as_po_filepath("/tmp/vampire_vs_pope_army-0.p8", "fr-FR"))
    end)
  end)
end)
