local io2 = require("io_utils")

describe("io_utils", function()
  describe(".dirname() & .basename()", function()
    it("should be complementary", function()
      local filepath = "/usr/local/etc/luarocks/config-5.3.lua"
      assert.equal(filepath, io2.dirname(filepath) .. "/" .. io2.basename(filepath))
    end)
  end)
  describe(".exists()", function()
    it("should return true for an existing directory", function()
      assert.True(io2.exists("tests"))
      assert.True(io2.exists("tests/"))
    end)
    it("should return true for an existing file", function()
      assert.True(io2.exists("tests/circle.p8"))
    end)
    it("should return false for a non-existing file", function()
      assert.False(io2.exists("i_do_not_exist"))
    end)
  end)
  describe(".copy()", function()
    it("should successfully copy an existing file", function()
      io2.copy("tests/circle.p8", "tests/dummy.p8")
      assert.True(io2.exists("tests/dummy.p8"))
      assert(os.remove("tests/dummy.p8"))
    end)
    it("should detect a non-existing source file", function()
      assert.has_error(function()
        assert.False(io2.copy("i_do_not_exist", "tests/dummy.p8"))
      end, "Could not read file: i_do_not_exist: No such file or directory")
    end)
  end)
  describe(".run()", function()
    it("should successfully run a basic command like echo", function()
      local output = io2.run("echo OK")
      assert.True(#output > 1)
    end)
    it("should detect a failure to run the command", function()
      assert.has_error(function()
        io2.run("i_do_not_exist")
      end, "Command 'i_do_not_exist' failed: exit - 127")
    end)
  end)
end)
