local p8_png = require("p8_png")

describe("p8_png", function()
  describe(".png_to_p8()", function()
    it("should convert a valid .p8.png file successfully", function()
      assert.has_error(function()
        p8_png.png_to_p8("dummy.p8.png")
      end, "WIP")
    end)
  end)

  describe(".p8_to_png()", function()
    it("should convert a valid .p8 file successfully", function()
      assert.has_error(function()
        p8_png.p8_to_png("dummy.p8")
      end, "WIP")
    end)
  end)

  describe(".with_png_converted()", function()
    it("should raise an error unknown file extensions", function()
      assert.has_error(function()
        p8_png.with_png_converted("dummy.pico8", function() end)
      end, "Unsupported file extension: dummy.pico8")
    end)
    it("should pass a .p8 file to the callback function when the input file is a PNG", function()
      assert.has_error(function()
        p8_png.with_png_converted("dummy.p8.png")
      end, "WIP")
    end)
  end)
end)
