local p8 = require("p8")

describe("p8", function()
  describe(".png_to_p8()", function()
    it("should convert a valid PICO8 game successfully", function()
      assert.has_error(function()
        p8.png_to_p8("dummy.p8.png")
      end, "WIP")
    end)
  end)
end)
