name: typos

on:  # cf. https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  sile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Spell Check Repo ✍️
        uses: crate-ci/typos@v1.42.1
